runtime: python37
entrypoint: gunicorn -b :$PORT --chdir ubyssey/ wsgi:application
instance_class: F4_1G

default_expiration: "365d"

automatic_scaling:
  max_idle_instances: 6
  target_cpu_utilization: .9

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: .*
  script: auto
  secure: always

vpc_access_connector:
  name: projects/ubyssey-prd/locations/us-central1/connectors/ubyssey-connector
