runtime: python39
entrypoint: gunicorn -b :$PORT --chdir ubyssey/ wsgi:application
instance_class: F4

default_expiration: "365d"

automatic_scaling:
  max_instances: 4

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: .*
  script: auto
  secure: always

vpc_access_connector:
  name: projects/ubyssey-prd/locations/us-central1/connectors/ubyssey-connector
