runtime: python37
env: flex
entrypoint: gunicorn -b :$PORT ubyssey:/ubyssey/wsgi.py

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /service-worker.js
  static_files: service-workers/service-worker.js
  upload: service-workers/service-worker.js
- url: .*
  script: auto
  secure: always

