runtime: python
env: flex
entrypoint: gunicorn -b :$PORT /ubyssey/views/main.py:/ubyssey/wsgi.py

runtime_config:
  python_version: 3

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /service-worker.js
  static_files: service-workers/service-worker.js
  upload: service-workers/service-worker.js
- url: .*
  script: auto
  secure: always

