runtime: python37
entrypoint: gunicorn -b :$PORT /ubyssey/views/main.py:/ubyssey/wsgi.py

automatic_scaling:
  target_cpu_utilization: .65
  max_instances: 100
  min_idle_instances: 2

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /service-worker.js
  static_files: service-workers/service-worker.js
  upload: service-workers/service-worker.js
- url: .*
  script: auto
  secure: always

